In [ ]:
import pandas as pd

In [ ]:
# https://dontpad.com/bcc-ds-02

df = pd.read_csv('https://raysonlaroca.github.io/' +
                 'teaching/data-science/datasets/enron.csv')

In [ ]:
df.head()

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value,name
0,4175000.0,2869717.0,-3081055.0,NaN,phillip.allen@enron.com,1729541.0,13868.0,2195.0,47.0,65.0,...,152.0,False,126027.0,-126027.0,201955.0,1407.0,2902.0,4484442.0,1729541.0,ALLEN PHILLIP K
1,NaN,178980.0,NaN,NaN,NaN,257817.0,3486.0,NaN,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,182466.0,257817.0,BADUM JAMES P
2,NaN,NaN,-5104.0,NaN,james.bannantine@enron.com,4046157.0,56301.0,29.0,39.0,0.0,...,864523.0,False,1757552.0,-560222.0,477.0,465.0,566.0,916197.0,5243487.0,BANNANTINE JAMES M
3,1200000.0,1295738.0,-1386055.0,NaN,NaN,6680544.0,11200.0,NaN,NaN,NaN,...,2660303.0,False,3942714.0,NaN,267102.0,NaN,NaN,5634343.0,10623258.0,BAXTER JOHN C
4,400000.0,260455.0,-201641.0,NaN,frank.bay@enron.com,NaN,129142.0,NaN,NaN,NaN,...,69.0,False,145796.0,-82782.0,239671.0,NaN,NaN,827696.0,63014.0,BAY FRANKLIN R

In [ ]:
# método de Tukey

for col in df.select_dtypes(include='number').columns.values:
    print(col)

bonus
deferral_payments
deferred_income
director_fees
exercised_stock_options
expenses
from_messages
from_poi_to_this_person
from_this_person_to_poi
loan_advances
long_term_incentive
other
restricted_stock
restricted_stock_deferred
salary
shared_receipt_with_poi
to_messages
total_payments
total_stock_value

In [ ]:
for col in df.select_dtypes(include='number').columns.values:
    print(col)

    # Q1 e Q3
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)

    # IQR (Q3 - Q1)
    iqr = q3 - q1

    # calcular o limite inferior e o superior (whiskers)
    k = 1.5 # valor "padrão" do método de Tukey (rule of thumb)
    # k = 3 # outliers extremos

    sup = q3 + k * iqr
    inf = q1 - k * iqr

    # obter os dados abaixo ou acima dos limites
    condicao = (df[col] < inf) | (df[col] > sup)
    idx_outliers_col = list(df[condicao].index)

    print(' ', idx_outliers_col, '\n')

bonus
  [0, 7, 31, 42, 75, 78, 79, 91, 122, 130, 139]

deferral_payments
  [0, 47, 66, 68, 130]

deferred_income
  [0, 7, 47, 59, 112, 130]

director_fees
  [8, 11, 94, 108, 130, 132]

exercised_stock_options
  [3, 32, 35, 47, 65, 79, 103, 110, 112, 122, 130, 144]

expenses
  [88, 116, 130, 132]

from_messages
  [0, 6, 7, 19, 31, 32, 58, 62, 66, 72, 73, 75, 78, 89, 116, 117, 139]

from_poi_to_this_person
  [7, 20, 26, 34, 37, 47, 58, 75, 78, 110, 139]

from_this_person_to_poi
  [0, 6, 7, 19, 31, 58, 72, 73, 75, 78, 89, 116, 117]

loan_advances
  []

long_term_incentive
  [40, 78, 79, 86, 130]

other
  [3, 47, 69, 77, 79, 86, 103, 119, 121, 130, 140]

restricted_stock
  [3, 11, 22, 47, 60, 69, 73, 79, 103, 112, 122, 130, 139, 140, 144]

restricted_stock_deferred
  [11, 32, 130]

salary
  [2, 32, 47, 57, 79, 105, 122, 130, 139]

shared_receipt_with_poi
  [7, 117]

to_messages
  [6, 7, 73, 75, 78, 117, 139]

total_payments
  [3, 7, 11, 31, 47, 78, 79, 86, 122, 130, 139]

total_stock_value
  [3, 32, 35, 41, 47, 65, 66, 79, 102, 103, 110, 112, 122, 130, 140, 144]

In [ ]:
outliers = []

for col in df.select_dtypes(include='number').columns.values:
    # print(col)

    # Q1 e Q3
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)

    # IQR (Q3 - Q1)
    iqr = q3 - q1

    # calcular o limite inferior e o superior (whiskers)
    k = 1.5 # valor "padrão" do método de Tukey
    # k = 3 # outliers extremos

    sup = q3 + k * iqr
    inf = q1 - k * iqr

    # obter os dados abaixo ou acima dos limites
    condicao = (df[col] < inf) | (df[col] > sup)
    idx_outliers_col = list(df[condicao].index)

    # print(' ', idx_outliers_col, '\n')

    # armazenar os outliers deste coluna
    for v in idx_outliers_col:
        outliers.append(v)

# lista com repetição dos outliers
print(outliers)

[0, 7, 31, 42, 75, 78, 79, 91, 122, 130, 139, 0, 47, 66, 68, 130, 0, 7, 47, 59, 112, 130, 8, 11, 94, 108, 130, 132, 3, 32, 35, 47, 65, 79, 103, 110, 112, 122, 130, 144, 88, 116, 130, 132, 0, 6, 7, 19, 31, 32, 58, 62, 66, 72, 73, 75, 78, 89, 116, 117, 139, 7, 20, 26, 34, 37, 47, 58, 75, 78, 110, 139, 0, 6, 7, 19, 31, 58, 72, 73, 75, 78, 89, 116, 117, 40, 78, 79, 86, 130, 3, 47, 69, 77, 79, 86, 103, 119, 121, 130, 140, 3, 11, 22, 47, 60, 69, 73, 79, 103, 112, 122, 130, 139, 140, 144, 11, 32, 130, 2, 32, 47, 57, 79, 105, 122, 130, 139, 7, 117, 6, 7, 73, 75, 78, 117, 139, 3, 7, 11, 31, 47, 78, 79, 86, 122, 130, 139, 3, 32, 35, 41, 47, 65, 66, 79, 102, 103, 110, 112, 122, 130, 140, 144]

In [ ]:
from collections import Counter

Counter(outliers)

Counter({0: 5,
         7: 8,
         31: 4,
         42: 1,
         75: 5,
         78: 7,
         79: 8,
         91: 1,
         122: 6,
         130: 13,
         139: 7,
         47: 9,
         66: 3,
         68: 1,
         59: 1,
         112: 4,
         8: 1,
         11: 4,
         94: 1,
         108: 1,
         132: 2,
         3: 5,
         32: 5,
         35: 2,
         65: 2,
         103: 4,
         110: 3,
         144: 3,
         88: 1,
         116: 3,
         6: 3,
         19: 2,
         58: 3,
         62: 1,
         72: 2,
         73: 4,
         89: 2,
         117: 4,
         20: 1,
         26: 1,
         34: 1,
         37: 1,
         40: 1,
         86: 3,
         69: 2,
         77: 1,
         119: 1,
         121: 1,
         140: 3,
         22: 1,
         60: 1,
         2: 1,
         57: 1,
         105: 1,
         41: 1,
         102: 1})

In [ ]:
Counter(outliers).most_common(10)

[(130, 13),
 (47, 9),
 (7, 8),
 (79, 8),
 (78, 7),
 (139, 7),
 (122, 6),
 (0, 5),
 (75, 5),
 (3, 5)]

In [ ]:
list_idx = [x[0] for x in Counter(outliers).most_common(10)]
list_idx

[130, 47, 7, 79, 78, 139, 122, 0, 75, 3]

In [ ]:
df.loc[list_idx]

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value,name
130,97343619.0,32083396.0,-27992891.0,1398517.0,NaN,311764000.0,5235198.0,NaN,NaN,NaN,...,42667589.0,False,130322299.0,-7576788.0,26704229.0,NaN,NaN,309886585.0,434509511.0,TOTAL
47,2000000.0,6426990.0,-3367011.0,NaN,mark.frevert@enron.com,10433518.0,86987.0,21.0,242.0,6.0,...,7427621.0,False,4188667.0,NaN,1060932.0,2979.0,3275.0,17252530.0,14622185.0,FREVERT MARK A
7,5249999.0,2144013.0,-2334434.0,NaN,tim.belden@enron.com,953136.0,17355.0,484.0,228.0,108.0,...,210698.0,True,157569.0,NaN,213999.0,5521.0,7991.0,5501630.0,1110705.0,BELDEN TIMOTHY N
79,7000000.0,202911.0,-300000.0,NaN,kenneth.lay@enron.com,34348384.0,99832.0,36.0,123.0,16.0,...,10359729.0,True,14761694.0,NaN,1072321.0,2411.0,4273.0,103559793.0,49110078.0,LAY KENNETH L
78,8000000.0,NaN,NaN,NaN,john.lavorato@enron.com,4158995.0,49537.0,2585.0,528.0,411.0,...,1552.0,False,1008149.0,NaN,339288.0,3962.0,7259.0,10425757.0,5167144.0,LAVORATO JOHN J
139,3000000.0,NaN,NaN,NaN,greg.whalley@enron.com,3282960.0,57838.0,556.0,186.0,24.0,...,301026.0,False,2796177.0,NaN,510364.0,3920.0,6019.0,4677574.0,6079137.0,WHALLEY LAWRENCE G
122,5600000.0,NaN,NaN,NaN,jeff.skilling@enron.com,19250000.0,29336.0,108.0,88.0,30.0,...,22122.0,True,6843672.0,NaN,1111258.0,2042.0,3627.0,8682716.0,26093672.0,SKILLING JEFFREY K
0,4175000.0,2869717.0,-3081055.0,NaN,phillip.allen@enron.com,1729541.0,13868.0,2195.0,47.0,65.0,...,152.0,False,126027.0,-126027.0,201955.0,1407.0,2902.0,4484442.0,1729541.0,ALLEN PHILLIP K
75,3100000.0,NaN,NaN,NaN,louise.kitchen@enron.com,81042.0,5774.0,1728.0,251.0,194.0,...,93925.0,False,466101.0,NaN,271442.0,3669.0,8305.0,3471141.0,547143.0,KITCHEN LOUISE
3,1200000.0,1295738.0,-1386055.0,NaN,NaN,6680544.0,11200.0,NaN,NaN,NaN,...,2660303.0,False,3942714.0,NaN,267102.0,NaN,NaN,5634343.0,10623258.0,BAXTER JOHN C

In [ ]:
df

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value,name
0,4175000.0,2869717.0,-3081055.0,NaN,phillip.allen@enron.com,1729541.0,13868.0,2195.0,47.0,65.0,...,152.0,False,126027.0,-126027.0,201955.0,1407.0,2902.0,4484442.0,1729541.0,ALLEN PHILLIP K
1,NaN,178980.0,NaN,NaN,NaN,257817.0,3486.0,NaN,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,182466.0,257817.0,BADUM JAMES P
2,NaN,NaN,-5104.0,NaN,james.bannantine@enron.com,4046157.0,56301.0,29.0,39.0,0.0,...,864523.0,False,1757552.0,-560222.0,477.0,465.0,566.0,916197.0,5243487.0,BANNANTINE JAMES M
3,1200000.0,1295738.0,-1386055.0,NaN,NaN,6680544.0,11200.0,NaN,NaN,NaN,...,2660303.0,False,3942714.0,NaN,267102.0,NaN,NaN,5634343.0,10623258.0,BAXTER JOHN C
4,400000.0,260455.0,-201641.0,NaN,frank.bay@enron.com,NaN,129142.0,NaN,NaN,NaN,...,69.0,False,145796.0,-82782.0,239671.0,NaN,NaN,827696.0,63014.0,BAY FRANKLIN R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,NaN,NaN,-25000.0,108579.0,NaN,NaN,1413.0,NaN,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,84992.0,NaN,WINOKUR JR. HERBERT S
142,NaN,NaN,NaN,NaN,john.wodraska@enron.com,NaN,NaN,NaN,NaN,NaN,...,189583.0,False,NaN,NaN,NaN,NaN,NaN,189583.0,NaN,WODRASKA JOHN
143,NaN,NaN,NaN,NaN,NaN,139130.0,NaN,NaN,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,139130.0,WROBEL BRUCE
144,NaN,NaN,NaN,NaN,scott.yeager@enron.com,8308552.0,53947.0,NaN,NaN,NaN,...,147950.0,True,3576206.0,NaN,158403.0,NaN,NaN,360300.0,11884758.0,YEAGER F SCOTT
145,NaN,NaN,NaN,NaN,NaN,192758.0,55097.0,NaN,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,55097.0,192758.0,YEAP SOON

# Isolation Forest

In [ ]:
from sklearn.ensemble import IsolationForest

In [ ]:
df.head()

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value,name
0,4175000.0,2869717.0,-3081055.0,NaN,phillip.allen@enron.com,1729541.0,13868.0,2195.0,47.0,65.0,...,152.0,False,126027.0,-126027.0,201955.0,1407.0,2902.0,4484442.0,1729541.0,ALLEN PHILLIP K
1,NaN,178980.0,NaN,NaN,NaN,257817.0,3486.0,NaN,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,182466.0,257817.0,BADUM JAMES P
2,NaN,NaN,-5104.0,NaN,james.bannantine@enron.com,4046157.0,56301.0,29.0,39.0,0.0,...,864523.0,False,1757552.0,-560222.0,477.0,465.0,566.0,916197.0,5243487.0,BANNANTINE JAMES M
3,1200000.0,1295738.0,-1386055.0,NaN,NaN,6680544.0,11200.0,NaN,NaN,NaN,...,2660303.0,False,3942714.0,NaN,267102.0,NaN,NaN,5634343.0,10623258.0,BAXTER JOHN C
4,400000.0,260455.0,-201641.0,NaN,frank.bay@enron.com,NaN,129142.0,NaN,NaN,NaN,...,69.0,False,145796.0,-82782.0,239671.0,NaN,NaN,827696.0,63014.0,BAY FRANKLIN R

In [ ]:
df_num = df.select_dtypes(include='number')
df_num

,bonus,deferral_payments,deferred_income,director_fees,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
0,4175000.0,2869717.0,-3081055.0,NaN,1729541.0,13868.0,2195.0,47.0,65.0,NaN,304805.0,152.0,126027.0,-126027.0,201955.0,1407.0,2902.0,4484442.0,1729541.0
1,NaN,178980.0,NaN,NaN,257817.0,3486.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182466.0,257817.0
2,NaN,NaN,-5104.0,NaN,4046157.0,56301.0,29.0,39.0,0.0,NaN,NaN,864523.0,1757552.0,-560222.0,477.0,465.0,566.0,916197.0,5243487.0
3,1200000.0,1295738.0,-1386055.0,NaN,6680544.0,11200.0,NaN,NaN,NaN,NaN,1586055.0,2660303.0,3942714.0,NaN,267102.0,NaN,NaN,5634343.0,10623258.0
4,400000.0,260455.0,-201641.0,NaN,NaN,129142.0,NaN,NaN,NaN,NaN,NaN,69.0,145796.0,-82782.0,239671.0,NaN,NaN,827696.0,63014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,NaN,NaN,-25000.0,108579.0,NaN,1413.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84992.0,NaN
142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189583.0,NaN,NaN,NaN,NaN,NaN,189583.0,NaN
143,NaN,NaN,NaN,NaN,139130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139130.0
144,NaN,NaN,NaN,NaN,8308552.0,53947.0,NaN,NaN,NaN,NaN,NaN,147950.0,3576206.0,NaN,158403.0,NaN,NaN,360300.0,11884758.0
145,NaN,NaN,NaN,NaN,192758.0,55097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55097.0,192758.0

In [ ]:
# imputação SIMPLES

df_num.fillna(0, inplace=True)
df_num

,bonus,deferral_payments,deferred_income,director_fees,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
0,4175000.0,2869717.0,-3081055.0,0.0,1729541.0,13868.0,2195.0,47.0,65.0,0.0,304805.0,152.0,126027.0,-126027.0,201955.0,1407.0,2902.0,4484442.0,1729541.0
1,0.0,178980.0,0.0,0.0,257817.0,3486.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,182466.0,257817.0
2,0.0,0.0,-5104.0,0.0,4046157.0,56301.0,29.0,39.0,0.0,0.0,0.0,864523.0,1757552.0,-560222.0,477.0,465.0,566.0,916197.0,5243487.0
3,1200000.0,1295738.0,-1386055.0,0.0,6680544.0,11200.0,0.0,0.0,0.0,0.0,1586055.0,2660303.0,3942714.0,0.0,267102.0,0.0,0.0,5634343.0,10623258.0
4,400000.0,260455.0,-201641.0,0.0,0.0,129142.0,0.0,0.0,0.0,0.0,0.0,69.0,145796.0,-82782.0,239671.0,0.0,0.0,827696.0,63014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,0.0,0.0,-25000.0,108579.0,0.0,1413.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84992.0,0.0
142,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,189583.0,0.0,0.0,0.0,0.0,0.0,189583.0,0.0
143,0.0,0.0,0.0,0.0,139130.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,139130.0
144,0.0,0.0,0.0,0.0,8308552.0,53947.0,0.0,0.0,0.0,0.0,0.0,147950.0,3576206.0,0.0,158403.0,0.0,0.0,360300.0,11884758.0
145,0.0,0.0,0.0,0.0,192758.0,55097.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55097.0,192758.0

In [ ]:
isof = IsolationForest(random_state=123)
isof.fit(df_num)

IsolationForest(random_state=123)

In [ ]:
y_pred = isof.predict(df_num)
y_pred

# 1 = valores "normais"
# -1 = outliers

array([ 1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [ ]:
df.insert(0, 'outlier', (y_pred == -1).astype(int))

In [ ]:
df.head()

,outlier,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,...,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value,name
0,0,4175000.0,2869717.0,-3081055.0,NaN,phillip.allen@enron.com,1729541.0,13868.0,2195.0,47.0,...,152.0,False,126027.0,-126027.0,201955.0,1407.0,2902.0,4484442.0,1729541.0,ALLEN PHILLIP K
1,0,NaN,178980.0,NaN,NaN,NaN,257817.0,3486.0,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,NaN,182466.0,257817.0,BADUM JAMES P
2,0,NaN,NaN,-5104.0,NaN,james.bannantine@enron.com,4046157.0,56301.0,29.0,39.0,...,864523.0,False,1757552.0,-560222.0,477.0,465.0,566.0,916197.0,5243487.0,BANNANTINE JAMES M
3,0,1200000.0,1295738.0,-1386055.0,NaN,NaN,6680544.0,11200.0,NaN,NaN,...,2660303.0,False,3942714.0,NaN,267102.0,NaN,NaN,5634343.0,10623258.0,BAXTER JOHN C
4,0,400000.0,260455.0,-201641.0,NaN,frank.bay@enron.com,NaN,129142.0,NaN,NaN,...,69.0,False,145796.0,-82782.0,239671.0,NaN,NaN,827696.0,63014.0,BAY FRANKLIN R

In [ ]:
condicao_outlier = df['outlier'] == 1
df[condicao_outlier]

,outlier,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,...,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value,name
7,1,5249999.0,2144013.0,-2334434.0,NaN,tim.belden@enron.com,953136.0,17355.0,484.0,228.0,...,210698.0,True,157569.0,NaN,213999.0,5521.0,7991.0,5501630.0,1110705.0,BELDEN TIMOTHY N
11,1,NaN,NaN,NaN,137864.0,sanjay.bhatnagar@enron.com,2604490.0,NaN,29.0,0.0,...,137864.0,False,-2604490.0,15456290.0,NaN,463.0,523.0,15456290.0,NaN,BHATNAGAR SANJAY
47,1,2000000.0,6426990.0,-3367011.0,NaN,mark.frevert@enron.com,10433518.0,86987.0,21.0,242.0,...,7427621.0,False,4188667.0,NaN,1060932.0,2979.0,3275.0,17252530.0,14622185.0,FREVERT MARK A
73,1,1000000.0,NaN,NaN,NaN,steven.kean@enron.com,2022048.0,41953.0,6759.0,140.0,...,1231.0,False,4131594.0,NaN,404338.0,3639.0,12754.0,1747522.0,6153642.0,KEAN STEVEN J
78,1,8000000.0,NaN,NaN,NaN,john.lavorato@enron.com,4158995.0,49537.0,2585.0,528.0,...,1552.0,False,1008149.0,NaN,339288.0,3962.0,7259.0,10425757.0,5167144.0,LAVORATO JOHN J
79,1,7000000.0,202911.0,-300000.0,NaN,kenneth.lay@enron.com,34348384.0,99832.0,36.0,123.0,...,10359729.0,True,14761694.0,NaN,1072321.0,2411.0,4273.0,103559793.0,49110078.0,LAY KENNETH L
122,1,5600000.0,NaN,NaN,NaN,jeff.skilling@enron.com,19250000.0,29336.0,108.0,88.0,...,22122.0,True,6843672.0,NaN,1111258.0,2042.0,3627.0,8682716.0,26093672.0,SKILLING JEFFREY K
130,1,97343619.0,32083396.0,-27992891.0,1398517.0,NaN,311764000.0,5235198.0,NaN,NaN,...,42667589.0,False,130322299.0,-7576788.0,26704229.0,NaN,NaN,309886585.0,434509511.0,TOTAL

In [ ]:
scores = isof.score_samples(df_num)
scores

array([-0.47272284, -0.30333765, -0.35504255, -0.4547111 , -0.33000846,
       -0.30922742, -0.44680748, -0.55541314, -0.31459292, -0.30606816,
       -0.32033822, -0.54751525, -0.31570695, -0.33349739, -0.33087094,
       -0.3370851 , -0.3161993 , -0.30588089, -0.30604745, -0.38779441,
       -0.35159162, -0.31798142, -0.33879106, -0.32720217, -0.3164338 ,
       -0.32781562, -0.33695638, -0.30289083, -0.30745522, -0.30090263,
       -0.32149477, -0.49146561, -0.44379245, -0.3443196 , -0.35343381,
       -0.34064815, -0.30634428, -0.33539524, -0.32303619, -0.31988105,
       -0.33326496, -0.34057713, -0.35545135, -0.39111531, -0.3089669 ,
       -0.3034392 , -0.30238492, -0.65333021, -0.3010428 , -0.30441948,
       -0.30862172, -0.30695024, -0.30945103, -0.30023979, -0.31808846,
       -0.31164429, -0.34414131, -0.31092609, -0.42684308, -0.40501447,
       -0.3123303 , -0.30581838, -0.35027491, -0.3105237 , -0.33030371,
       -0.42926728, -0.41251751, -0.30586187, -0.36020779, -0.34652823,
       -0.3113621 , -0.33164355, -0.45735626, -0.53134908, -0.32274967,
       -0.43871676, -0.34597628, -0.33441793, -0.60682989, -0.72053306,
       -0.34651032, -0.32762797, -0.3071655 , -0.30813841, -0.30023979,
       -0.30374398, -0.43448535, -0.31515489, -0.35757888, -0.37707101,
       -0.31104534, -0.36435228, -0.32602265, -0.31484089, -0.3186294 ,
       -0.32885313, -0.30310326, -0.30250811, -0.34562454, -0.30903328,
       -0.31469299, -0.31890327, -0.32256222, -0.4232379 , -0.32696739,
       -0.38178922, -0.3415742 , -0.3023371 , -0.31520662, -0.30711272,
       -0.37550717, -0.32705411, -0.48650221, -0.32504559, -0.34713984,
       -0.29904339, -0.37860229, -0.48021272, -0.34847464, -0.32999359,
       -0.31240827, -0.38145046, -0.55901553, -0.30403102, -0.30507521,
       -0.33670198, -0.31595966, -0.30405587, -0.32098999, -0.32066748,
       -0.86687492, -0.30812089, -0.3627535 , -0.34464094, -0.33607861,
       -0.30144485, -0.3316    , -0.31271717, -0.30023979, -0.46368831,
       -0.4209454 , -0.32541364, -0.30030546, -0.30023979, -0.34538757,
       -0.30276032])

In [ ]:
df.insert(1, 'outlier_score', isof.score_samples(df_num))

In [ ]:
df[condicao_outlier]

,outlier,outlier_score,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,...,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value,name
7,1,-0.555413,5249999.0,2144013.0,-2334434.0,NaN,tim.belden@enron.com,953136.0,17355.0,484.0,...,210698.0,True,157569.0,NaN,213999.0,5521.0,7991.0,5501630.0,1110705.0,BELDEN TIMOTHY N
11,1,-0.547515,NaN,NaN,NaN,137864.0,sanjay.bhatnagar@enron.com,2604490.0,NaN,29.0,...,137864.0,False,-2604490.0,15456290.0,NaN,463.0,523.0,15456290.0,NaN,BHATNAGAR SANJAY
47,1,-0.653330,2000000.0,6426990.0,-3367011.0,NaN,mark.frevert@enron.com,10433518.0,86987.0,21.0,...,7427621.0,False,4188667.0,NaN,1060932.0,2979.0,3275.0,17252530.0,14622185.0,FREVERT MARK A
73,1,-0.531349,1000000.0,NaN,NaN,NaN,steven.kean@enron.com,2022048.0,41953.0,6759.0,...,1231.0,False,4131594.0,NaN,404338.0,3639.0,12754.0,1747522.0,6153642.0,KEAN STEVEN J
78,1,-0.606830,8000000.0,NaN,NaN,NaN,john.lavorato@enron.com,4158995.0,49537.0,2585.0,...,1552.0,False,1008149.0,NaN,339288.0,3962.0,7259.0,10425757.0,5167144.0,LAVORATO JOHN J
79,1,-0.720533,7000000.0,202911.0,-300000.0,NaN,kenneth.lay@enron.com,34348384.0,99832.0,36.0,...,10359729.0,True,14761694.0,NaN,1072321.0,2411.0,4273.0,103559793.0,49110078.0,LAY KENNETH L
122,1,-0.559016,5600000.0,NaN,NaN,NaN,jeff.skilling@enron.com,19250000.0,29336.0,108.0,...,22122.0,True,6843672.0,NaN,1111258.0,2042.0,3627.0,8682716.0,26093672.0,SKILLING JEFFREY K
130,1,-0.866875,97343619.0,32083396.0,-27992891.0,1398517.0,NaN,311764000.0,5235198.0,NaN,...,42667589.0,False,130322299.0,-7576788.0,26704229.0,NaN,NaN,309886585.0,434509511.0,TOTAL