In [ ]:
import pandas as pd

In [ ]:
# https://dontpad.com/bcc-ds-02

# Carregando o conjunto de dados de um arquivo .csv
# df -> DataFrame
df = pd.read_csv('https://raysonlaroca.github.io/' +
                 'teaching/data-science/datasets/salaries.csv')

In [ ]:
df

     Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0             1      Prof          B             19           18  Male  139750
1             2      Prof          B             20           16  Male  173200
2             3  AsstProf          B              4            3  Male   79750
3             4      Prof          B             45           39  Male  115000
4             5      Prof          B             40           41  Male  141500
..          ...       ...        ...            ...          ...   ...     ...
392         393      Prof          A             33           30  Male  103106
393         394      Prof          A             31           19  Male  150564
394         395      Prof          A             42           25  Male  101738
395         396      Prof          A             25           15  Male   95329
396         397  AsstProf          A              8            4  Male   81035

[397 rows x 7 columns]

In [ ]:
# Exibe um resumo estrutural do DataFrame: número de entradas, nomes das colunas,
# quantidade de valores não nulos em cada coluna e os tipos de dados (dtypes).
# Também mostra o uso aproximado de memória do DataFrame.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     397 non-null    int64
 1   rank           397 non-null    object
 2   discipline     397 non-null    object
 3   yrs.since.phd  397 non-null    int64
 4   yrs.service    397 non-null    int64
 5   sex            397 non-null    object
 6   salary         397 non-null    int64
dtypes: int64(4), object(3)
memory usage: 21.8+ KB

In [ ]:
# retorna uma tupla com o formato do DataFrame:
# (número de linhas, número de colunas)

df.shape

# df.shape[0]  # Retorna apenas o número de linhas

(397, 7)

In [ ]:
# retorna os nomes das colunas do dataset
df.columns

Index(['Unnamed: 0', 'rank', 'discipline', 'yrs.since.phd', 'yrs.service',
       'sex', 'salary'],
      dtype='object')

In [ ]:
# Exibe as primeiras linhas do DataFrame (head).
# Por padrão mostra 5 linhas; aqui mostramos apenas 3.
df.head(3)

   Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B             19           18  Male  139750
1           2      Prof          B             20           16  Male  173200
2           3  AsstProf          B              4            3  Male   79750

In [ ]:
# Exibe as últimas linhas do DataFrame (tail).
# Por padrão mostra 5 linhas; aqui mostramos apenas 3.
df.tail(3)

     Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
394         395      Prof          A             42           25  Male  101738
395         396      Prof          A             25           15  Male   95329
396         397  AsstProf          A              8            4  Male   81035

In [ ]:
# Seleciona a coluna 'salary' do DataFrame.
# O resultado é uma Series (estrutura unidimensional do pandas).
df['salary']

0      139750
1      173200
2       79750
3      115000
4      141500
        ...
392    103106
393    150564
394    101738
395     95329
396     81035
Name: salary, Length: 397, dtype: int64

In [ ]:
df.head()

   Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B             19           18  Male  139750
1           2      Prof          B             20           16  Male  173200
2           3  AsstProf          B              4            3  Male   79750
3           4      Prof          B             45           39  Male  115000
4           5      Prof          B             40           41  Male  141500

In [ ]:
# Selecionar N colunas?
df[['sex', 'salary']]

      sex  salary
0    Male  139750
1    Male  173200
2    Male   79750
3    Male  115000
4    Male  141500
..    ...     ...
392  Male  103106
393  Male  150564
394  Male  101738
395  Male   95329
396  Male   81035

[397 rows x 2 columns]

In [ ]:
# Como verificar se existem valores faltantes no DataFrame?

df.isna()

# Retorna um DataFrame com o mesmo formato do original,
# onde cada elemento é um valor booleano (True para valores faltantes).

     Unnamed: 0   rank  discipline  yrs.since.phd  yrs.service    sex  salary
0         False  False       False          False        False  False   False
1         False  False       False          False        False  False   False
2         False  False       False          False        False  False   False
3         False  False       False          False        False  False   False
4         False  False       False          False        False  False   False
..          ...    ...         ...            ...          ...    ...     ...
392       False  False       False          False        False  False   False
393       False  False       False          False        False  False   False
394       False  False       False          False        False  False   False
395       False  False       False          False        False  False   False
396       False  False       False          False        False  False   False

[397 rows x 7 columns]

In [ ]:
# Conta o número de valores ausentes em cada coluna do DataFrame
df.isna().sum()

Unnamed: 0       0
rank             0
discipline       0
yrs.since.phd    0
yrs.service      0
sex              0
salary           0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     397 non-null    int64
 1   rank           397 non-null    object
 2   discipline     397 non-null    object
 3   yrs.since.phd  397 non-null    int64
 4   yrs.service    397 non-null    int64
 5   sex            397 non-null    object
 6   salary         397 non-null    int64
dtypes: int64(4), object(3)
memory usage: 21.8+ KB

In [ ]:
df.head(3)

   Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B             19           18  Male  139750
1           2      Prof          B             20           16  Male  173200
2           3  AsstProf          B              4            3  Male   79750

In [ ]:
# Gera um resumo estatístico das colunas numéricas do DataFrame
df.describe()

# Inclui métricas como média, desvio padrão, mínimo, máximo e quartis
# Considera apenas colunas numéricas

       Unnamed: 0  yrs.since.phd  yrs.service         salary
count  397.000000     397.000000   397.000000     397.000000
mean   199.000000      22.314861    17.614610  113706.458438
std    114.748275      12.887003    13.006024   30289.038695
min      1.000000       1.000000     0.000000   57800.000000
25%    100.000000      12.000000     7.000000   91000.000000
50%    199.000000      21.000000    16.000000  107300.000000
75%    298.000000      32.000000    27.000000  134185.000000
max    397.000000      56.000000    60.000000  231545.000000

In [ ]:
df['salary'].quantile(0.25) # 1º quartil

np.float64(91000.0)

In [ ]:
df['salary'].quantile(0.5) # 2º quartil

np.float64(107300.0)

In [ ]:
df['salary'].median()

107300.0

In [ ]:
df['salary'].quantile(0.75) # 3º quartil

np.float64(134185.0)

In [ ]:
df.head(5)

   Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B             19           18  Male  139750
1           2      Prof          B             20           16  Male  173200
2           3  AsstProf          B              4            3  Male   79750
3           4      Prof          B             45           39  Male  115000
4           5      Prof          B             40           41  Male  141500

In [ ]:
df.columns

Index(['Unnamed: 0', 'rank', 'discipline', 'yrs.since.phd', 'yrs.service',
       'sex', 'salary'],
      dtype='object')

In [ ]:
# Às vezes queremos remover uma coluna do DataFrame

df.drop('Unnamed: 0', axis=1)  # axis=1 indica remoção de coluna
df.head(3) # a coluna ainda permanece pois a operação não foi atribuída

   Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B             19           18  Male  139750
1           2      Prof          B             20           16  Male  173200
2           3  AsstProf          B              4            3  Male   79750

In [ ]:
# Remove a coluna 'Unnamed: 0' e salva o resultado em um novo DataFrame
df_new = df.drop('Unnamed: 0', axis=1)

# Visualiza as primeiras linhas do novo DataFrame
# (agora sim -> sem a coluna removida)
df_new.head(3)

       rank discipline  yrs.since.phd  yrs.service   sex  salary
0      Prof          B             19           18  Male  139750
1      Prof          B             20           16  Male  173200
2  AsstProf          B              4            3  Male   79750

In [ ]:
# Remove a coluna 'Unnamed: 0' diretamente do DataFrame original
# inplace=True aplica a alteração no próprio df
df.drop('Unnamed: 0', axis=1, inplace=True)

# Visualiza as primeiras linhas do DataFrame já atualizado
df.head()

       rank discipline  yrs.since.phd  yrs.service   sex  salary
0      Prof          B             19           18  Male  139750
1      Prof          B             20           16  Male  173200
2  AsstProf          B              4            3  Male   79750
3      Prof          B             45           39  Male  115000
4      Prof          B             40           41  Male  141500

In [ ]:
# E se tentarmos remover uma coluna que não existe?
# Nesse caso, o pandas gera um erro porque a coluna não foi encontrada.
df.drop('Unnamed: 0', axis=1, inplace=True)  # erro

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
# errors='ignore' evita erro caso a coluna não exista
df.drop('Unnamed: 0', axis=1, inplace=True, errors='ignore')

In [ ]:
df.tail()

         rank discipline  yrs.since.phd  yrs.service   sex  salary
392      Prof          A             33           30  Male  103106
393      Prof          A             31           19  Male  150564
394      Prof          A             42           25  Male  101738
395      Prof          A             25           15  Male   95329
396  AsstProf          A              8            4  Male   81035

In [ ]:
# Seleção condicional
# Exemplo: professores(as) que lecionam a disciplina A

condicao = df['discipline'] == 'A'  # cria uma máscara booleana
df[condicao]  # retorna apenas as linhas que satisfazem a condição

         rank discipline  yrs.since.phd  yrs.service     sex  salary
17       Prof          A             38           34    Male  103450
18       Prof          A             37           23    Male  124750
19       Prof          A             39           36  Female  137000
20       Prof          A             31           26    Male   89565
21       Prof          A             36           31    Male  102580
..        ...        ...            ...          ...     ...     ...
392      Prof          A             33           30    Male  103106
393      Prof          A             31           19    Male  150564
394      Prof          A             42           25    Male  101738
395      Prof          A             25           15    Male   95329
396  AsstProf          A              8            4    Male   81035

[181 rows x 6 columns]

In [ ]:
# Seleção condicional direta (mesmo resultado)
df[df['discipline'] == 'A']

         rank discipline  yrs.since.phd  yrs.service     sex  salary
17       Prof          A             38           34    Male  103450
18       Prof          A             37           23    Male  124750
19       Prof          A             39           36  Female  137000
20       Prof          A             31           26    Male   89565
21       Prof          A             36           31    Male  102580
..        ...        ...            ...          ...     ...     ...
392      Prof          A             33           30    Male  103106
393      Prof          A             31           19    Male  150564
394      Prof          A             42           25    Male  101738
395      Prof          A             25           15    Male   95329
396  AsstProf          A              8            4    Male   81035

[181 rows x 6 columns]

In [ ]:
# Seleção condicional composta (E / OU)
# Exemplo: professorAs que lecionam a disciplina A

condicao = df['discipline'] == 'A' and df['sex'] == 'Female'
df[condicao] # erro

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# As condições precisam estar isoladas entre parênteses,
# mas ainda assim "and" não funciona com Series do pandas
condicao = (df['discipline'] == 'A') and (df['sex'] == 'Female')
df[condicao]  # erro
# Em pandas devemos usar & para "E" e | para "OU"

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# Operadores lógicos em pandas:
# "and" (Python)  ->  &
# "or"  (Python)  ->  |
# "not" (Python)  ->  ~

condicao = (df['discipline'] == 'A') & (df['sex'] == 'Female')
df[condicao]  # retorna apenas as linhas que satisfazem ambas as condições

          rank discipline  yrs.since.phd  yrs.service     sex  salary
19        Prof          A             39           36  Female  137000
24   AssocProf          A             13            8  Female   74830
114       Prof          A             12            0  Female  105000
119   AsstProf          A              5            3  Female   73500
123  AssocProf          A             25           22  Female   62884
127   AsstProf          A              2            0  Female   72500
132  AssocProf          A             10            8  Female   77500
133   AsstProf          A              3            1  Female   72500
230       Prof          A             29           27  Female   91000
231  AssocProf          A             26           24  Female   73300
233       Prof          A             36           19  Female  117555
237   AsstProf          A              7            6  Female   63100
245       Prof          A             17           11  Female   90450
253   AsstProf          A              4            2  Female   77500
254       Prof          A             28            7  Female  116450
274   AsstProf          A              8            3  Female   78500
358       Prof          A             28           14  Female  109954
361       Prof          A             23           15  Female  109646

In [ ]:
# Também podemos aplicar a condição diretamente no DataFrame
df[(df['discipline'] == 'A') | (df['sex'] == 'Female')]

         rank discipline  yrs.since.phd  yrs.service     sex  salary
9        Prof          B             18           18  Female  129000
17       Prof          A             38           34    Male  103450
18       Prof          A             37           23    Male  124750
19       Prof          A             39           36  Female  137000
20       Prof          A             31           26    Male   89565
..        ...        ...            ...          ...     ...     ...
392      Prof          A             33           30    Male  103106
393      Prof          A             31           19    Male  150564
394      Prof          A             42           25    Male  101738
395      Prof          A             25           15    Male   95329
396  AsstProf          A              8            4    Male   81035

[202 rows x 6 columns]

In [ ]:
# Acessa o valor da coluna 'rank' na linha de índice 396
df.loc[396]['rank']

'AsstProf'

In [ ]:
# A ordem inversa também funciona:
# primeiro selecionamos a coluna e depois acessamos o índice da linha
df['rank'].loc[396]

'AsstProf'

In [ ]:
df.head(3)

       rank discipline  yrs.since.phd  yrs.service   sex  salary
0      Prof          B             19           18  Male  139750
1      Prof          B             20           16  Male  173200
2  AsstProf          B              4            3  Male   79750

In [ ]:
# Compara cada elemento do DataFrame com o valor 20
# O resultado é um DataFrame booleano (True onde o valor é 20)
df == 20

      rank  discipline  yrs.since.phd  yrs.service    sex  salary
0    False       False          False        False  False   False
1    False       False           True        False  False   False
2    False       False          False        False  False   False
3    False       False          False        False  False   False
4    False       False          False        False  False   False
..     ...         ...            ...          ...    ...     ...
392  False       False          False        False  False   False
393  False       False          False        False  False   False
394  False       False          False        False  False   False
395  False       False          False        False  False   False
396  False       False          False        False  False   False

[397 rows x 6 columns]

In [ ]:
df.head()

       rank discipline  yrs.since.phd  yrs.service   sex  salary
0      Prof          B             19           18  Male  139750
1      Prof          B             20           16  Male  173200
2  AsstProf          B              4            3  Male   79750
3      Prof          B             45           39  Male  115000
4      Prof          B             40           41  Male  141500

In [ ]:
# Salário médio das professorAs que lecionam a disciplina B
condicao = (df['discipline'] == 'B') & (df['sex'] == 'Female')

# Seleciona os salários das linhas que satisfazem a condição e calcula a média
df[condicao]['salary'].mean()

np.float64(111234.52380952382)

In [ ]:
# Ordenação

# df.sort_values('salary', ascending=True)
df.sort_values('salary', ascending=False)

          rank discipline  yrs.since.phd  yrs.service     sex  salary
43        Prof          B             38           38    Male  231545
364       Prof          A             43           43    Male  205500
249       Prof          A             29            7    Male  204000
271       Prof          A             42           18    Male  194800
77        Prof          B             26           19    Male  193000
..         ...        ...            ...          ...     ...     ...
317       Prof          B             46           45    Male   67559
226   AsstProf          A              3            1    Male   63900
237   AsstProf          A              7            6  Female   63100
123  AssocProf          A             25           22  Female   62884
282       Prof          A             51           51    Male   57800

[397 rows x 6 columns]

In [ ]:
# Ordenação por múltiplas colunas
# Primeiro pela disciplina e depois pelo salário

# Quando há mais de uma coluna, precisamos passar uma lista
df.sort_values(['discipline', 'salary'])

          rank discipline  yrs.since.phd  yrs.service     sex  salary
282       Prof          A             51           51    Male   57800
123  AssocProf          A             25           22  Female   62884
237   AsstProf          A              7            6  Female   63100
226   AsstProf          A              3            1    Male   63900
240   AsstProf          A              5            3    Male   69200
..         ...        ...            ...          ...     ...     ...
350       Prof          B             56           49    Male  186960
198       Prof          B             34           33    Male  189409
330       Prof          B             49           60    Male  192253
77        Prof          B             26           19    Male  193000
43        Prof          B             38           38    Male  231545

[397 rows x 6 columns]

In [ ]:
# A ordem das colunas importa na ordenação
# Primeiro ordena por 'salary' e, em caso de empate, por 'discipline'
df.sort_values(['salary', 'discipline'])

          rank discipline  yrs.since.phd  yrs.service     sex  salary
282       Prof          A             51           51    Male   57800
123  AssocProf          A             25           22  Female   62884
237   AsstProf          A              7            6  Female   63100
226   AsstProf          A              3            1    Male   63900
317       Prof          B             46           45    Male   67559
..         ...        ...            ...          ...     ...     ...
77        Prof          B             26           19    Male  193000
271       Prof          A             42           18    Male  194800
249       Prof          A             29            7    Male  204000
364       Prof          A             43           43    Male  205500
43        Prof          B             38           38    Male  231545

[397 rows x 6 columns]

In [ ]:
# Podemos usar formas de ordenação diferentes para cada coluna
# Aqui ordenamos 'discipline' em ordem crescente
# e 'salary' em ordem decrescente
df.sort_values(['discipline', 'salary'], ascending=[True, False])

          rank discipline  yrs.since.phd  yrs.service     sex  salary
364       Prof          A             43           43    Male  205500
249       Prof          A             29            7    Male  204000
271       Prof          A             42           18    Male  194800
389       Prof          A             33           18    Male  186023
292       Prof          A             39            9    Male  183800
..         ...        ...            ...          ...     ...     ...
75    AsstProf          B              8            3    Male   73266
316  AssocProf          B             12            9  Female   71065
49    AsstProf          B              1            1    Male   70768
64    AsstProf          B              4            3    Male   68404
317       Prof          B             46           45    Male   67559

[397 rows x 6 columns]

In [ ]:
# Estatísticas

df['salary'].mean()

np.float64(113706.45843828715)

In [ ]:
df['salary'].min(), df['salary'].max()

(57800, 231545)

In [ ]:
df['discipline'].mode()

0    B
Name: discipline, dtype: object

In [ ]:
print(df['salary'].median())
print(df['salary'].std())

107300.0
30289.038694747804

In [ ]:
# Existe diferença no salário médio
# entre professores homens e mulheres?

condicao_m = df['sex'] == 'Male'
condicao_f = df['sex'] == 'Female'

print('Male:  ', df[condicao_m]['salary'].mean())
print('Female:', df[condicao_f]['salary'].mean())

Male:   115090.41899441341
Female: 101002.41025641025

In [ ]:
# Também podemos calcular isso de outra forma usando GroupBy
# Agrupa os dados pela coluna 'sex' e calcula o salário médio de cada grupo
df.groupby('sex')['salary'].mean()

sex
Female    101002.410256
Male      115090.418994
Name: salary, dtype: float64

In [ ]:
# GroupBy permite analisar os dados em diferentes níveis de granularidade
# Aqui agrupamos por 'sex' e 'rank' e calculamos o salário médio de cada grupo
df.groupby(['sex', 'rank'])['salary'].mean()

sex     rank
Female  AssocProf     88512.800000
        AsstProf      78049.909091
        Prof         121967.611111
Male    AssocProf     94869.703704
        AsstProf      81311.464286
        Prof         127120.822581
Name: salary, dtype: float64

In [ ]:
# Contagem de registros em cada grupo
# Agrupa por 'sex' e 'rank' e conta quantos valores
# de 'salary' existem em cada grupo
df.groupby(['sex', 'rank'])['salary'].count()

sex     rank
Female  AssocProf     10
        AsstProf      11
        Prof          18
Male    AssocProf     54
        AsstProf      56
        Prof         248
Name: salary, dtype: int64

In [ ]:
# E se quisermos mais de uma estatística ao mesmo tempo?
# O método agg permite aplicar várias funções de agregação

df.groupby(['sex', 'rank'])['salary'].agg(['mean', 'median', 'count'])

                           mean    median  count
sex    rank
Female AssocProf   88512.800000   90556.5     10
       AsstProf    78049.909091   77000.0     11
       Prof       121967.611111  120257.5     18
Male   AssocProf   94869.703704   95626.5     54
       AsstProf    81311.464286   80182.0     56
       Prof       127120.822581  123996.0    248

In [ ]:
# Construção de novas variáveis a partir das existentes
# (Feature Engineering)

In [ ]:
df.head()

       rank discipline  yrs.since.phd  yrs.service   sex  salary
0      Prof          B             19           18  Male  139750
1      Prof          B             20           16  Male  173200
2  AsstProf          B              4            3  Male   79750
3      Prof          B             45           39  Male  115000
4      Prof          B             40           41  Male  141500

In [ ]:
# Calcula, linha a linha, a diferença entre os anos desde o doutorado
# e os anos de serviço
df['yrs.since.phd'] - df['yrs.service']

0       1
1       4
2       1
3       6
4      -1
       ..
392     3
393    12
394    17
395    10
396     4
Length: 397, dtype: int64

In [ ]:
# Podemos criar uma nova coluna
df['dif_phd_service'] = df['yrs.since.phd'] - df['yrs.service']

In [ ]:
df.head()

,rank,discipline,yrs.since.phd,yrs.service,sex,salary,dif_phd_service
0,Prof,B,19,18,Male,139750,1
1,Prof,B,20,16,Male,173200,4
2,AsstProf,B,4,3,Male,79750,1
3,Prof,B,45,39,Male,115000,6
4,Prof,B,40,41,Male,141500,-1

In [ ]:
# quais são os valores únicos de uma coluna?
df['discipline'].unique()

array(['B', 'A'], dtype=object)

In [ ]:
df['salary'].nunique()
# insight: há alguns salários que se repetem na base!

371

In [ ]:
# Conta quantas vezes cada cargo aparece
df['rank'].value_counts()

rank
Prof         266
AsstProf      67
AssocProf     64
Name: count, dtype: int64

In [ ]:
# percentual
df['rank'].value_counts() / len(df)

rank
Prof         0.670025
AsstProf     0.168766
AssocProf    0.161209
Name: count, dtype: float64

In [ ]:
df.head()

,rank,discipline,yrs.since.phd,yrs.service,sex,salary,dif_phd_service
0,Prof,B,19,18,Male,139750,1
1,Prof,B,20,16,Male,173200,4
2,AsstProf,B,4,3,Male,79750,1
3,Prof,B,45,39,Male,115000,6
4,Prof,B,40,41,Male,141500,-1

In [ ]:
# Aplica uma função a cada valor da coluna 'rank'
# para substituir as abreviações por nomes completos

def tratamento(x):
    if x == 'Prof':
        return 'Professor'
    elif x == 'AsstProf':
        return 'Professor Assistente'
    else:
        return 'Professor Associado'

df['rank'] = df['rank'].apply(tratamento)

In [ ]:
df.head()

,rank,discipline,yrs.since.phd,yrs.service,sex,salary,dif_phd_service
0,Professor,B,19,18,Male,139750,1
1,Professor,B,20,16,Male,173200,4
2,Professor Assistente,B,4,3,Male,79750,1
3,Professor,B,45,39,Male,115000,6
4,Professor,B,40,41,Male,141500,-1

In [ ]:
# Tratamento usando mais de uma coluna
# Exemplo: True se 'sex' == 'Male' e 'salary' > 150000

def tratamento_duas_colunas(r):
    return r['sex'] == 'Male' and r['salary'] > 150000

# axis=1 faz com que a função seja aplicada linha a linha
df['condicao_duas_colunas'] = df.apply(tratamento_duas_colunas, axis=1)

df.head()

,rank,discipline,yrs.since.phd,yrs.service,sex,salary,dif_phd_service,condicao_duas_colunas
0,Professor,B,19,18,Male,139750,1,False
1,Professor,B,20,16,Male,173200,4,True
2,Professor Assistente,B,4,3,Male,79750,1,False
3,Professor,B,45,39,Male,115000,6,False
4,Professor,B,40,41,Male,141500,-1,False